# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: mysql2
  encoding: utf8
  database: socialboost
  username: sato
  password: Satohide1994@
  host: 118.27.3.195
  port: 3306

test:
  <<: *default

production:
  <<: *default
  adapter: mysql2
  encoding: utf8
  database: socialboost
  username: root
  password:
  host: localhost
  socket: /tmp/mysql.sock
